In [8]:
import pandas  as pd
import numpy as np

In [9]:
released_in=pd.read_csv('/Users/macbook/Desktop/BA6/Database/db2018imdb/release_dates.csv', sep=',')
len(released_in)

2113649

In [10]:
released_in=pd.read_csv('/Users/macbook/Desktop/BA6/Database/db2018imdb/release_dates.csv', sep=',', error_bad_lines=False)
released_in.rename(columns={'ReleaseCountry': 'CountryName'}, inplace=True)
released_in[['CountryName']] = released_in[['CountryName']].fillna(value='Other')
released_in.dropna(subset=['ReleaseDate','ClipId'], inplace=True)

countries=pd.read_csv('/Users/macbook/Desktop/BA6/Database/newfiles/countries.csv', sep=',', error_bad_lines=False)
released_in= pd.merge(released_in, countries, how='left', on='CountryName')
released_in[['countid']]=released_in[['countid']].fillna(value = 223)
released_in.drop(['CountryName'],axis=1,inplace=True)
released_in['ReleaseDate'] = released_in['ReleaseDate'].str.extract('(\d{4})')
released_in['ReleaseDate']=released_in['ReleaseDate'].astype(int)
released_in['did']=(released_in.ReleaseDate).rank(method='dense')

/Applications/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:10: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  # Remove the CWD from sys.path while we load stuff.

In [11]:
Releasedates = released_in[['did','ReleaseDate']].copy()
Releasedates.drop_duplicates(keep='first', inplace=True)
Releasedates.to_csv('Releasedates.csv', sep=',', encoding='utf-8', index=False)

In [15]:
x=Releasedates[Releasedates['did']==2]
x

         did  ReleaseDate
1225954  2.0         1893

In [13]:
released_in.drop(['ReleaseDate'], axis=1, inplace=True)


released_in.drop_duplicates(keep='first', inplace=True)
released_in

          ClipId  countid    did
0              4     33.0  119.0
1        1773811    203.0  115.0
2        1773815    203.0  115.0
3        1773818    203.0  115.0
4        1773820    203.0  115.0
5        1773823    203.0  115.0
6        1773827    203.0  115.0
7        1773829    203.0  115.0
8        1773833    203.0  115.0
9        1773837    203.0  115.0
10       1773840    203.0  120.0
11       1773841    203.0  120.0
12       1773843    203.0  119.0
13       1773844    203.0  120.0
14       1773846    203.0  119.0
15       1773850    203.0  119.0
16       1773854    203.0  120.0
17       1773855    203.0  119.0
18       1773856    203.0  120.0
19       1773857    203.0  119.0
21       1773860    203.0  119.0
22       1773863    203.0  119.0
24       1773866    203.0  120.0
25       1773869    203.0  119.0
26       1773870    203.0  119.0
28       1773872    203.0  120.0
29       1773873    203.0  119.0
30       1773875    203.0  119.0
31       1773880     33.0  110.0
32       1773884    203.0   93.0
...          ...      ...    ...
2113614  1773738    157.0  118.0
2113616  1773738    136.0  118.0
2113617  1773738     33.0  118.0
2113619  1773738    189.0  118.0
2113620  1773738    164.0  118.0
2113622  1773738    125.0  118.0
2113623  1773738    183.0  118.0
2113624  1773738    188.0  118.0
2113627  1773738     88.0  118.0
2113628  1773738      7.0  120.0
2113629  1773746    199.0   93.0
2113630  1773751    199.0   84.0
2113631  1773763    199.0   72.0
2113632  1773771    203.0  108.0
2113633  1773771    199.0  108.0
2113634  1773771     73.0  108.0
2113635  1773771     33.0  112.0
2113636  1773771    157.0  119.0
2113637  1773787     86.0  120.0
2113638  1773784     86.0  115.0
2113639  1773784    203.0  116.0
2113640  1773789     86.0   82.0
2113641  1773793     86.0  112.0
2113642  1773795     86.0  114.0
2113643  1773795     45.0  114.0
2113644  1773796     86.0  119.0
2113645  1773799     26.0  119.0
2113646  1773802    125.0  111.0
2113647  1773804    125.0  117.0
2113648  1773807    203.0  116.0

[2021266 rows x 3 columns]

In [14]:
released_in.to_csv('released_in.csv', sep=',', encoding='utf-8', index=False)